# Generated by Django 4.0.5 on 2022-10-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='texto',
            field=models.TextField(),
        ),
    ]
