# Generated by Django 4.0.5 on 2022-10-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Seccion",
        ),
    ]
