# Generated by Django 4.0.5 on 2022-10-12 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0002_delete_seccion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reseña",
            name="articulo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Blog.articulo",
            ),
        ),
    ]
