# Generated by Django 4.0.5 on 2022-10-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0003_alter_reseña_articulo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lector",
            old_name="profesion",
            new_name="nivel",
        ),
    ]
